[package]
name = "gcmake-rust"
version = "1.0.0"
authors = ["Skylar Cupit <skylarcupit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
path-clean = "0.1.0"
clap = "3.0.0-beta.4"
regex = "1"

[profile.release]
lto = true
strip = true
