[package]
name = "gcmake-rust"
version = "1.4.0"
authors = ["Skylar Cupit <skylarcupit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.26"
path-clean = "0.1.0"
clap = { version = "3.2.13", features = ["derive"] }
regex = "1.6.0"
lazy_static = "1.4.0"
enum-iterator = "1.1.3"
base64ct = { version = "1.5.2", features = ["alloc"] }
colored = "2.0.0"

[profile.release]
lto = true
strip = true
